version: "3.8"

services:

  app1:
    image: nginx:alpine
    container_name: app1
    volumes:
      - ./app1:/usr/share/nginx/html:ro
    networks:
      - web

  app2:
    image: nginx:alpine
    container_name: app2
    volumes:
      - ./app2:/usr/share/nginx/html:ro
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: gateway-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - web

networks:
  web: