events {}

http {

  upstream app1 {
    server app1:80;
  }

  upstream app2 {
    server app2:80;
  }

  server {
    listen 80;

    # Route to App 1
    location /app1/ {
      proxy_pass http://app1/;
      proxy_set_header Host $host;
    }

    # Route to App 2
    location /app2/ {
      proxy_pass http://app2/;
      proxy_set_header Host $host;
    }

    # Default page
    location / {
      return 200 "Welcome to Nginx Gateway 🚀 Use /app1 or /app2";
    }
  }
}